apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-app
  namespace: scraper
  labels:
    app: scraper-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper-app
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: scraper-app
    spec:
      containers:
        - name: scraper-app
          image: medicardcr001.azurecr.io/scraper-app:2.2.1-staging
          env:
            - name: NODE_ENV
              value: staging
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
      - name: myregistry