apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-queue
  namespace: scraper
  labels:
    app: scraper-queue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scraper-queue
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: scraper-queue
    spec:
      volumes:
        - name: scraper-pv
          persistentVolumeClaim:
            claimName: scraper-pvc
      containers:
        - name: scraper-queue
          image: medicardcr001.azurecr.io/scraper-queue:2.2.1-staging
          env:
            - name: NODE_ENV
              value: staging
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/scraper-captures"
              name: scraper-pv
      imagePullSecrets:
      - name: myregistry